library(shiny)
dados=read.csv2("energia.csv",header=T)
saida=dados[,2:6]
rownames(saida)=dados[,1]
shinyServer(function(input,output){ 
  output$table<-renderTable(
    summary(as.numeric(as.matrix(subset(saida,select=input$class))))
  )
})
